### ISSUE TITLE
3 package.json files

### ISSUE THREAD

**Issue by rajikaimal** [99xt/serverless-boilerplate#26]
Will it affect the structure of the boilerplate, if package.json files gets merged somehow ?

**Comment by mjzone** [comment]
@rajikaimal The intention of using separate package.json files, is to facilitate decoupled deployment of client and backend. For example if you want to deploy the client in heroku, you can easily do so by introducing 'npm start' for the client package.json file. Similarly the backend package.json carries the dependencies for the lambdas. However when it comes to development, we wouldn't want to run commands by navigating to each folder. Outer package.json is used to ease this process and leverage offline server and dynamodb local features.

**Comment by rajikaimal** [comment]
Got it !, closing this issue now 😃
