### ISSUE TITLE
Developed Authentication Per User

### ISSUE THREAD

**Issue by jcummins54** [99xt/serverless-boilerplate#35]
I've forked the latest version of the aws-react branch as of today (11/02/2016) and integrated with the serverless-authentication-boilerplate. Features are:

- Writes user data to user table.
- Authenticates per user so that one user cannot modify another's data.
- Authenticates user before responding with auth token to prevent hacking.
- Added linting ("npm run lint" from root folder)

Working demo here: http://sls-react-auth.s3-website-us-east-1.amazonaws.com/ (facebook login only). 

See: https://github.com/jcummins54/serverless-react-boilerplate
and https://github.com/jcummins54/serverless-authentication-boilerplate

Would be happy to collaborate to make this a branch here.

**Comment by mjzone** [comment]
@jcummins54 This is great ✨ I have created [react-authenticate](https://github.com/99xt/serverless-react-boilerplate/tree/react-authenticate) branch and sent you an invitation for the team. So you can commit directly to this branch.

**Comment by jcummins54** [comment]
Awesome, thanks!
