### ISSUE TITLE
offline doesn't create table.

### ISSUE THREAD

**Issue by xkguq007** [99xt/serverless-boilerplate#39]
I follow exactly same, However it doesn't work.
'''
Serverless: Failure: Error: ResourceNotFoundException: Cannot do operations on a non-existent table
'''
this is why failed.

I searched a little, 

'''
custom:
  stage: ${opt:stage, self:provider.stage}
  dynamodb:
    start:
      migration: true
    migration:
      dir: offline/migrations
      table_prefix: ${self:custom.stage}
  writeEnvVars:
    REMOTE_STAGE: ${self:custom.stage}
'''

that part, migration: true, migration: dir: offline/...
is this really works??
Examples what I found are make table's information in serverless.yml using 'resource'

**Comment by mjzone** [comment]
@xkguq007 Boilerplate is updated to latest serverless version and serverless-dynamodb-local version.

**Comment by xkguq007** [comment]
Oh, I forgot close this issue. @mjzone is right. I was used wrong version of serverless framework.
thanks.
